var zj;
(function (zj) {
    zj.StringConfig_Table = {
        // item
        itemNone: "item_table_none",
        itemGeneral: "table_item_general",
        itemRes: "table_item_resource",
        itemProp: "table_item_prop",
        itemSoul: "table_item_general_soul",
        itemPartner: "table_item_partner",
        itemPartnerSplit: "table_item_partner_split",
        itemEquipForge: "table_item_equip_forge",
        itemEquipCarve: "table_item_equip_carve",
        itemFormation: "table_item_formation",
        itemCollect: "table_item_collect",
        itemCimelia: "table_item_cimelia",
        itemHead: "table_item_pic",
        itemFrame: "table_item_pic_frame",
        itemTitle: "table_item_title",
        itemSecret: "table_item_secret",
        itemFashion: "table_item_fashion",
        itemJade: "table_item_jade",
        itemTransfer: "table_item_transfer",
        itemPotato: "table_item_potato",
        itemClient: "table_item_client",
        pic: "table_pic",
        // teach
        story: "client_table_story",
        storyTeach: "client_table_story_teach",
        teach: "table_teach",
        // client
        cssSource: "client_table_ani_css_source",
        spineSource: "client_table_ani_spine_source",
        particleSource: "client_table_ani_particle_source",
        spxSource: "client_table_ani_spx_source",
        ui: "client_table_ani_ui",
        hurtDisplacement: "client_table_hurt_displacement",
        actionDisplacement: "client_table_action_displacement",
        // actionUnit          : "table_action_unit",
        mapAi: "client_table_map_ai",
        mapBg: "client_table_map_bg",
        skillAction: "table_skill_action",
        skillBuff: "table_skill_buff",
        hunterAwake: "table_hunter_awake",
        skillDisplacement: "client_table_skill_displacement",
        skillEffects: "table_skill_effects",
        skillHitEffect: "client_table_skill_hiteffect",
        skillHurt: "table_skill_hurt",
        skillParticle: "client_table_skill_particle",
        skillShake: "client_table_skill_shake",
        skillStep: "client_table_skill_step",
        skillUnit: "table_skill_unit",
        buffBase: "client_table_buff_base",
        formats: "table_formations",
        errorLua: "client_table_error",
        log: "client_table_log",
        fightCombo: "client_table_fight_combo",
        typeFrom: "client_table_get_prop",
        typePackage: "client_type_package",
        typeRank: "client_type_rank",
        soundRes: "client_table_sound_resource",
        bgmRes: "client_table_bgm_resource",
        groupFight: "table_instance_group",
        //未改的
        skillBase: "table_general_skill",
        itemEquipment: "table_item_equipment",
        //未知的
        unknow1: "table_name_auto",
        unknow2: "table_battle_buff",
        unknow3: "table_activity_buff",
        unknow5: "table_item_general",
        chest: "table_chest",
        randItem: "table_rand_item",
        process: "table_process",
        itemBase: "table_item_base",
        level: "table_level",
        vip: "table_licence",
        vipWeal: "table_licence_weal",
        vipHalo: "table_halo",
        LowVip: "table_vipinfo",
        LowVipWeal: "table_vip_weal",
        talk: "client_table_ui_talk",
        rule: "client_table_ui_rule",
        mine: "table_mine",
        money: "table_buy_money",
        hunter_ani_spine: "client_table_fight_ani_spine_source",
        mapRole: "table_map_role",
        monsterInstance: "table_monster_instance",
        monsterTower: "table_monster_tower",
        monsterVillage: "table_monster_village",
        monsterWanted: "table_monster_wanted",
        monsterLocal: "client_table_monsterLocal",
        bossInformation: "client_table_boss_information",
        funOpen: "table_function_open",
        missionActive: "table_mission_active",
        missionType: "table_mission_type",
        missionItem: "table_mission_item",
        missionLicense: "table_mission_licence",
        missionMain: "table_mission_main",
        chapterNORMAL: "table_chapter_normal",
        chapterELITE: "table_chapter_elite",
        chapterSearch: "table_instance_search",
        instance: "table_instance",
        instance_village: "table_instance_village",
        stage: "table_stage",
        train: "table_training",
        chestInstance: "table_instance_chest",
        adviserBase: "table_base_adviser",
        adviserEquip: "table_adviser_equip",
        adviserLevel: "table_adviser_level",
        strategyCompo: "table_strategy_compose",
        strategyAttri: "table_strategy_attri",
        petBase: "table_base_pet",
        petSkill: "table_pet_skill",
        baseGeneral: "table_base_general",
        baseStep: "table_general_step",
        baseHole: "table_general_hole",
        baseEquip: "table_general_equip",
        baseSkill: "table_general_skill",
        baseTalent: "table_general_talent",
        talentEffect: "table_general_talent_effect",
        generalStar: "table_general_star",
        generalQuality: "table_general_quality",
        generalEquipCarve: "table_general_equip_carve",
        generalCompose: "table_general_compose",
        generalAwake: "table_hunter_awake",
        arenaScore: "table_ladder_score",
        singleScore: "table_singlecraft_score",
        singleRankSelf: "table_singlecraft_rank_self",
        singleRank: "table_singlecraft_rank",
        fastMall: "table_quick_mall",
        tower: "table_tower",
        leagueDonate: "table_league_donate",
        leagueSkill: "table_league_skill",
        leagueAnimal: "table_league_animals",
        leagueBoss: "table_league_boss",
        leagueAnimalChat: "client_table_league_animal_chat",
        leagueFish: "table_league_fish",
        leagueInstance: "table_league_instance",
        leagueFightBuild: "table_league_war_build",
        leagueWarChest: "table_league_war_chest",
        leagueWarRank: "table_league_war_rank",
        WonderBossReward: "table_scene_boss_reward",
        Runes: "table_runes",
        worldBoss: "client_table_world_boss",
        activityBossMap: "table_activityboss_map_block",
        wonderlandMap: "table_wonderland_map_block",
        wonderTree: "table_wonderland_tree",
        wonderland: "table_wonderland",
        darklandlandMap: "table_darkland_map_block",
        darklandland: "table_darkland",
        darklandPortAward: "table_darkland_rank_reward",
        relicInstance: "table_instance_relic",
        relicInstanceChest: "table_instance_relic_chest",
        spineNpc: "client_table_npc",
        pay: "table_pay_index",
        channel_pay: "table_channel_pay",
        mineInfo: "table_mine_info",
        mineShovel: "table_mine_shovel",
        wanted: "table_wanted",
        wanted_Enamy: "table_wanted_enemy_camp",
        wanted_mobs_feature: "client_table_wanted_mobs_feature",
        wanted_rand: "table_wanted_rand",
        buff: "table_buff",
        gift: "table_gift",
        fund: "table_fund_reward",
        activity: "client_table_activity",
        continue_login: "table_continue_login",
        newGift_seven: "table_newgift_seven",
        //删除的
        //immortal            : "table_immortal",                 // 访仙
        itemTalentBook: "table_item_talent",
        itemTalentSplit: "table_item_talent_split",
        spGeneral: "table_spgeneral_reward",
        artifact: "table_base_artifact",
        jade: "table_jade_hole",
        jade_gamble: "table_gamble_jade",
        firstcharge: "table_first_charge",
        powerLevel: "client_table_power_level",
        evilZone: "table_evil_zone",
        contendRank: "table_contend_rank",
        contendSection: "table_contend_section",
        language: "table_language",
        facebookShare: "table_facebook",
        rankReward: "table_praise_reward",
        worldBossMap: "table_worldboss_map_block",
        recovery: "table_recovery",
        potatoFate: "table_potato_fate",
        potatoAttri: "table_potato_attri",
        pay_benefit: "table_pay_benefit",
        potatoBreak: "table_potato_break",
        new_gift: "table_newgift",
        new_gift_item: "table_newgift_item",
        new_gift_days: "table_newgift_daily",
        new_gift_items: "table_monthgift",
        new_gift_index: "client_table_monthgift_index",
        uplevel_rewerd: "table_uplevel_reward",
        color_fruit_reward: "table_color_fruit_reward",
        convert: "table_exchange_mall",
        commound: "table_general_make",
        general_life: "table_general_life",
        general_life_statpoints: "table_general_life_statpoints",
        instance_area: "table_instance_area",
        league_boss_reward: "table_league_boss_reward",
        egg_random: "table_integral_egg",
        xuyuan_random: "table_xuyuan",
        general_psychic_attri: "table_general_psychic_attri",
        general_psychic: "table_general_psychic",
        hunter_break: "table_general_breakup",
        hunter_break_attri: "table_general_break",
        raceAward: "table_mission_race",
        raceMission: "table_mission_main",
        jewelMission: "table_mission_jewel",
        leagueMatchScore: "table_league_match_score",
        leagueMatchRank: "table_league_match_rank",
        shareTable: "table_share_reward",
        //help
        help_info: "client_table_help",
        help_big_type: "client_table_help_big_type",
        help_small_type: "client_table_help_small_type",
    };
    zj.StringConfig_Language = (_a = {},
        _a[0] = "en",
        _a[1] = "ch",
        _a[2] = "tw",
        _a[4] = "ja",
        _a[5] = "ko",
        _a);
    zj.StringConfig_Language_Server = (_b = {},
        _b[0] = "en",
        _b[1] = "zhcn",
        _b[2] = "zhtw",
        _b[3] = "id",
        _b[4] = "ja",
        _b[5] = "ko",
        _b[6] = "th",
        _b[7] = "vi",
        _b);
    zj.StringConfig_Common = {
        defaultFontName: "ssof.ttf",
        unknownError: "unknow error",
        slash: "%s/%s",
        multi: "x%s",
        percent: "%d%%",
        skip: (_c = {},
            _c[1] = "跳过",
            _c[2] = "skip",
            _c),
    };
    zj.StringConfig_Teach = {
        name: (_d = {},
            _d[1] = "双双",
            _d),
        dialog: (_e = {},
            _e[1] = "@，恭喜你终于得到大家的承认，能申请加入公会了！你可以从公会列表中选择一个公会加入，也能自己创建一个公会！有了公会之后，好处多多！",
            _e[2] = "进公会之后，你能和大家一起刷小怪开宝箱，一起推公会Boss，还能获得加成大量属性的公会兵法技能，得到各种炫酷的公会称号和公会时装！@，还等什么，快加入公会吧！",
            _e),
    };
    zj.StringConfig_Login = {
        stateColor: ["r:238,g:238,b:210",
            "r:0,g:255,b:0",
            "r:240,g:49,b:3",
            "r:255,g:0,b:0"]
    };
    zj.StringConfig_Save = {
        lotteryTenTip: "lottery_ten_tip",
        swordSoulTenTip: "swordsoul_ten_tip",
        strengthenTip: "strengthen_gold_tip",
        markTip: "mark_gold_tip",
        petStrengthenTip: "pet_strengthen_gold_tip",
        bgmusic: "bgmusic_switch",
        soundeffect: "soundeffect_switch",
        languageType: "language_type",
        defaultlanguageType: "default_type",
        // login
        account_str: "a_str",
        password_str: "p_str",
        quicklogin: "quick_login",
        savepwd: "save_password",
        autologin: "auto_login",
        bindAccount: "bind_account",
        isDemoAccount_str: "isDemoAccount",
        login_server_str: "server",
        isNewLogin_str: "isNewLogin",
        device_id_str: "device_id",
        isAutoRegist_str: "auto_regist_acount",
        firstLogin: "first_login",
        teachOpen: "teach_open",
        battleValidate: "battleValidate",
        debug: "debug",
        devlog: "devlog",
        showMp4Once: "show_mp4_once",
        showWarCheats: "show_war_cheats",
        firstPlayVideo: "show_video",
        // worship set
        worship_start: "worship_start",
        wonderland_first_open: "_Wonderland_first_open_",
        fish_first_open: "_Fish_first_open",
        wonderland_head_tips: "_Wonderland_HeadTips",
        fastBattleHideTips: "_fastBattle_HideTips",
        fastBattleSwitch: "_fastBattle_Switch",
        fastRunesSwitch: "_fastRunes_Switch",
        //system set
        system: (_f = {},
            _f[1] = (_g = {},
                _g[1] = "bgmusic_switch",
                _g[2] = "soundeffect_switch",
                _g[3] = "sytem_particle",
                _g[4] = "system_undefine1",
                _g[5] = "system_Detail",
                _g),
            _f[2] = (_h = {},
                _h[1] = "system_power",
                _h[2] = "system_mall",
                _h[3] = "system_activity",
                _h[4] = "system_undefine2",
                _h),
            _f),
        // for bug use
        // power fix bug
        power_bug: "power_bug",
        plate_bug: "plate_bug",
        // mall fix bug
        mall_bug: "mall_bug",
        // fix mission bug
        mission_bug: "mission_bug",
        // main mission new state
        main_mission_new: "main_mission_new",
        // 第一次接主线任务
        main_mission_first: "main_mission_first",
        //查看主线任务完成
        main_mission_over_view: "main_mission_over_view",
        //公会战提示
        union_battle_pop: "union_battle_pop",
        firstWebPay: "first_web_pay"
    };
    zj.StringConfig_NpcSpine = {
        league: "banghuinpc",
        worship: "fangxiannpc",
        bastille_1: "funiunpc1",
        bastille_2: "funiunpc2",
        tavern_1: "jiuguannpc1",
        tavern_2: "jiuguangnpc2",
        mall_1: "putongnpc",
        mall_2: "shenminpc",
        arena: "yanwunpc",
        treasure: "animation",
        daily: "animation",
    };
    zj.StringConfig_NumberEffect = {
        jingyan: "jingyannum",
        baoji: "baojinum",
        shanghai1: "shanghainum1",
        shanghai2: "shanghainum2",
        ewaishanghai: "ewaishanghainum",
        combo: "combonum",
    };
    // 天梯
    zj.StringConfig_Tower = {};
    zj.StringConfig_Chat = {
        none: "点击此处输入聊天内容(1-38个字)",
        world: "世 界",
        private: "私 聊",
        union: "公 会",
        title: ["[系统]",
            "[世界]",
            "[公会]",
            "[私聊]",
            "[任务]",
            "[公告]"]
    };
    zj.StringConfig_Instance = {
        boxSuffix: ["Wood",
            "Silver",
            "Gold"]
    };
    zj.StringConfig_ErrorCode = {};
    zj.StringConfig_TagType = {
        chat: (_j = {},
            _j["World"] = 1,
            _j["Server"] = 2,
            _j["League"] = 3,
            _j["Whisper"] = 4,
            _j),
        friend: (_k = {},
            _k["Friend"] = 1,
            _k["Enemy"] = 2,
            _k),
        leagueBefore: (_l = {},
            _l["Join"] = 1,
            _l["Create"] = 2,
            _l),
        leagueManage: (_m = {},
            _m["Application"] = 1,
            _m["MsgSet"] = 2,
            _m),
        chooseServer: (_o = {},
            _o["Mine"] = 1,
            _o["Recommend"] = 2,
            _o["List"] = 3,
            _o),
        formatChoose: (_p = {},
            _p["generals"] = 1,
            _p["reserves"] = 2,
            _p["supports"] = 3,
            _p),
        mineAll: (_q = {},
            _q["Dig"] = 1,
            _q["Rob"] = 2,
            _q["Def"] = 3,
            _q),
        mineDef: (_r = {},
            _r["Invite"] = 1,
            _r["INGMain"] = 2,
            _r),
        mineDefING: (_s = {},
            _s["Info"] = 1,
            _s["None"] = 2,
            _s),
        mineRob: (_t = {},
            _t["Normal"] = 1,
            _t["Enemy"] = 2,
            _t),
        mineDigInvite: (_u = {},
            _u["League"] = 1,
            _u["Friend"] = 2,
            _u),
        adviser: (_v = {},
            _v["Law"] = 1,
            _v["Skill"] = 2,
            _v),
    };
    zj.StringConfig_TagString = {
        chat: (_w = {},
            _w[1] = "World",
            _w[2] = "Ally",
            _w[3] = "Whisper",
            _w[4] = "Wanted",
            _w),
        friend: (_x = {},
            _x[1] = "Friend",
            _x[2] = "Enemy",
            _x),
        leagueBefore: (_y = {},
            _y[1] = "Join",
            _y[2] = "Create",
            _y),
        leagueManage: (_z = {},
            _z[1] = "Application",
            _z[2] = "MsgSet",
            _z),
        chooseServer: (_0 = {},
            _0[1] = "Mine",
            _0[2] = "Recommend",
            _0[3] = "List",
            _0),
        formatChoose: (_1 = {},
            _1[1] = "generals",
            _1[2] = "reserves",
            _1[3] = "supports",
            _1),
        mineAll: (_2 = {},
            _2[1] = "Dig",
            _2[2] = "Rob",
            _2[3] = "Def",
            _2),
        mineDef: (_3 = {},
            _3[1] = "Invite",
            _3[2] = "INGMain",
            _3),
        mineDefING: (_4 = {},
            _4[1] = "Info",
            _4[2] = "None",
            _4),
        mineRob: (_5 = {},
            _5[1] = "Normal",
            _5[2] = "Enemy",
            _5),
        mineDigInvite: (_6 = {},
            _6[1] = "League",
            _6[2] = "Friend",
            _6),
        adviser: (_7 = {},
            _7[1] = "Law",
            _7[2] = "Skill",
            _7)
    };
    var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y, _z, _0, _1, _2, _3, _4, _5, _6, _7;
})(zj || (zj = {}));
//# sourceMappingURL=StringConfig.js.map