namespace zj {
export enum EnumPlayerState {
    PLAYER_STATE_NONE = 0,
    PLAYER_STATE_LEADER = 1,
    PLAYER_STATE_FIGHT_LEADER = 2,
    PLAYER_STATE_ZORK_LEADER = 3,
    PLAYER_STATE_OTHER = 4,
    PLAYER_STATE_ZORK_OTHER = 5, 
    PLAYER_STATE_FIGHT_OTHER = 6,   
    PLAYER_STATE_ANIMAL = 7,
    PLAYER_STATE_BOSS = 8,
}
}